trigger:
- master
- develop
- feature/*

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  dotNetVersion: '6.0.x'
  dotNetFramework: 'net6.0'
  targetRuntime: 'linux-x64'

steps:
- task: gittools.gittools.setup-gitversion-task.gitversion/setup@0
  displayName: gitversion/setup
  inputs:
    versionSpec: 5.x
    includePrerelease: true

- task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
  displayName: gitversion/execute

- bash: |
    npm install -g eclint
    eclint check
  displayName: "eclint check" 

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Get-ChildItem env:
      $projectKey=$(BUILD.REPOSITORY.NAME).Replace('/','_')
- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: sonarcloud.io
    organization: 'janono-pub'
    projectKey: '$projectKey'
    projectName: '$(BUILD.REPOSITORY.NAME)'

- task: UseDotNet@2
  inputs:
    version: $(dotNetVersion)
    includePreviewVersions: true

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'

- script: dotnet pack  --configuration $(buildConfiguration) --include-symbols --output '$(Build.ArtifactStagingDirectory)'
  displayName: 'dotnet pack'

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'
- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'janono.ado.testcase.associate'
  enabled: false
  continueOnError: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org_janono.ado.testcase.associate'
  enabled: false
  continueOnError: true